#!/bin/bash
# Open puzzle creator

echo "🎨 Opening Puzzle Creator..."
open ../puzzle_reviewer/puzzle_creator.html

echo ""
echo "✨ Puzzle Creator Features:"
echo ""
echo "📋 Three Workflows:"
echo "   1. CREATE FROM SCRATCH"
echo "      - Drag pieces onto board"
echo "      - Click pieces to add/remove"
echo "      - Set turn to move"
echo "      - Add solution moves and hint"
echo "      - Save to library"
echo ""
echo "   2. EDIT IMPORTED PUZZLES"
echo "      - Import tab → Load puzzle file"
echo "      - Click puzzle to edit"
echo "      - Modify position on board"
echo "      - Update moves/hint"
echo "      - Save changes"
echo ""
echo "   3. BUILD LIBRARY"
echo "      - Save multiple puzzles"
echo "      - Edit anytime from 'My Puzzles' tab"
echo "      - Export all when done"
echo ""
echo "💾 Your puzzles auto-save in browser storage!"
echo "📥 Export when ready to use in app"
