#!/bin/bash
# Open puzzle editor with instructions

echo "✨ Opening puzzle editor (with visual chessboard)..."
open ../puzzle_reviewer/review_ui_with_editor.html

echo ""
echo "🎨 Puzzle Editor Features:"
echo "   - Visual chessboard for each puzzle"
echo "   - Edit FEN positions"
echo "   - Modify solution moves"
echo "   - Change hints"
echo "   - Track changes with visual indicators"
echo ""
echo "📍 To load puzzles:"
echo "   1. Click 'Choose File'"
echo "   2. Navigate to: $(pwd)/output/"
echo "   3. Select a level_XXXX_candidates.json file"
echo ""
echo "✏️  To edit a puzzle:"
echo "   1. Click 'Edit Puzzle' button"
echo "   2. Modify FEN, moves, or hint"
echo "   3. Click 'Save Changes'"
echo "   4. Changes marked with ✏️ icon"
echo ""
echo "💾 Export options:"
echo "   - 'Export Selected': Only selected puzzles (final format)"
echo "   - 'Export All': All puzzles with edits applied"
echo ""
echo "🎯 Goal: Select 15 best puzzles, edit if needed, then export!"
