#!/bin/bash
# Open check/checkmate position editor

echo "♔ Opening Check/Checkmate Position Editor..."
open ../puzzle_reviewer/check_checkmate_editor.html

echo ""
echo "📋 Check/Checkmate Editor Features:"
echo "   - Visual chessboard for each position"
echo "   - Edit FEN positions with live preview"
echo "   - Change answer (check vs checkmate)"
echo "   - Modify descriptions"
echo "   - Add new positions"
echo "   - Delete positions"
echo ""
echo "📍 To load positions:"
echo "   1. Click 'Choose File'"
echo "   2. Navigate to: /Users/Sharpnacks/chess-training-app/assets/data/games/"
echo "   3. Select 'check_checkmate_positions.json'"
echo ""
echo "✏️  To edit a position:"
echo "   1. Click 'Edit Position' button"
echo "   2. Modify FEN, answer, or description"
echo "   3. Use 'Preview FEN' to see changes on board"
echo "   4. Click 'Save Changes'"
echo "   5. Changes marked with ✏️ icon"
echo ""
echo "➕ To add new positions:"
echo "   1. Click '➕ Add New Position'"
echo "   2. Edit the new position"
echo "   3. Save changes"
echo ""
echo "💾 Export options:"
echo "   - Click 'Export All Positions' to download edited file"
echo "   - Replace the original file in assets/data/games/ if satisfied"
echo ""
