name: ChessTrainerApp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: any


flutter:
  uses-material-design: true

  assets:
    - assets/data/levels/
    - assets/data/puzzles/
    - assets/data/bots/
    - assets/schemas/

